name: blossomd
description: A Blossom protocol server implementation for blob storage with Nostr authentication.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  sqlite3: ^2.4.6
  crypto: ^3.0.3
  secp256k1: ^0.3.0
  path: ^1.9.0
  convert: ^3.1.1
  http: ^1.1.0
  bip340: ^0.3.0
  dotenv: ^4.2.0
  bech32: ^0.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
